coverage:
  status:
    project:
      default:
        target: 80%
  ignore:
    - "proto/**"
    - "vendor/**"
    - "**/generated/**"
    - "**/*.gen.go"
    - "**/testdata/**"
    - "/internal/service/client/auth_view.go"
    - "/internal/service/client/main_view.go"
    - "/internal/service/client/add_view.go"
    - "/internal/service/client/data_view.go"
    - "/internal/service/client/version_view.go"
    - "/internal/service/client/modal.go"
    - "/internal/client/crypto.go"
    - "/migrations/**"
