coverage:
  status:
    project:
      default:
        target: 80%
  ignore:
    - "proto/**"
    - "vendor/**"
    - "**/generated/**"
    - "**/*.gen.go"
    - "**/testdata/**"
    - "migrations/**"
    - "certs/**"
    - "cmd/staticlint/**"
