// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/service/client/card_service.go
//
// Generated by this command:
//
//	mockgen -source=./internal/service/client/card_service.go -destination ./internal/service/client/mock_card_service_test.go -package client
//

// Package client is a generated GoMock package.
package client

import (
	reflect "reflect"

	v1 "github.com/Stern-Ritter/gophkeeper/proto/gen/gophkeeper/gophkeeperapi/v1"
	gomock "go.uber.org/mock/gomock"
)

// MockCardService is a mock of CardService interface.
type MockCardService struct {
	ctrl     *gomock.Controller
	recorder *MockCardServiceMockRecorder
}

// MockCardServiceMockRecorder is the mock recorder for MockCardService.
type MockCardServiceMockRecorder struct {
	mock *MockCardService
}

// NewMockCardService creates a new mock instance.
func NewMockCardService(ctrl *gomock.Controller) *MockCardService {
	mock := &MockCardService{ctrl: ctrl}
	mock.recorder = &MockCardServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCardService) EXPECT() *MockCardServiceMockRecorder {
	return m.recorder
}

// CreateCard mocks base method.
func (m *MockCardService) CreateCard(number, owner, expiry, cvc, pin, comment string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCard", number, owner, expiry, cvc, pin, comment)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateCard indicates an expected call of CreateCard.
func (mr *MockCardServiceMockRecorder) CreateCard(number, owner, expiry, cvc, pin, comment any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCard", reflect.TypeOf((*MockCardService)(nil).CreateCard), number, owner, expiry, cvc, pin, comment)
}

// DeleteCard mocks base method.
func (m *MockCardService) DeleteCard(cardID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCard", cardID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCard indicates an expected call of DeleteCard.
func (mr *MockCardServiceMockRecorder) DeleteCard(cardID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCard", reflect.TypeOf((*MockCardService)(nil).DeleteCard), cardID)
}

// GetAllCards mocks base method.
func (m *MockCardService) GetAllCards() ([]*v1.CardV1, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllCards")
	ret0, _ := ret[0].([]*v1.CardV1)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllCards indicates an expected call of GetAllCards.
func (mr *MockCardServiceMockRecorder) GetAllCards() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllCards", reflect.TypeOf((*MockCardService)(nil).GetAllCards))
}
