// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/service/client/text_service.go
//
// Generated by this command:
//
//	mockgen -source=./internal/service/client/text_service.go -destination ./internal/service/client/mock_text_service_test.go -package client
//

// Package client is a generated GoMock package.
package client

import (
	reflect "reflect"

	v1 "github.com/Stern-Ritter/gophkeeper/proto/gen/gophkeeper/gophkeeperapi/v1"
	gomock "go.uber.org/mock/gomock"
)

// MockTextService is a mock of TextService interface.
type MockTextService struct {
	ctrl     *gomock.Controller
	recorder *MockTextServiceMockRecorder
}

// MockTextServiceMockRecorder is the mock recorder for MockTextService.
type MockTextServiceMockRecorder struct {
	mock *MockTextService
}

// NewMockTextService creates a new mock instance.
func NewMockTextService(ctrl *gomock.Controller) *MockTextService {
	mock := &MockTextService{ctrl: ctrl}
	mock.recorder = &MockTextServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTextService) EXPECT() *MockTextServiceMockRecorder {
	return m.recorder
}

// CreateText mocks base method.
func (m *MockTextService) CreateText(text, comment string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateText", text, comment)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateText indicates an expected call of CreateText.
func (mr *MockTextServiceMockRecorder) CreateText(text, comment any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateText", reflect.TypeOf((*MockTextService)(nil).CreateText), text, comment)
}

// DeleteText mocks base method.
func (m *MockTextService) DeleteText(textID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteText", textID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteText indicates an expected call of DeleteText.
func (mr *MockTextServiceMockRecorder) DeleteText(textID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteText", reflect.TypeOf((*MockTextService)(nil).DeleteText), textID)
}

// GetAllTexts mocks base method.
func (m *MockTextService) GetAllTexts() ([]*v1.TextV1, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllTexts")
	ret0, _ := ret[0].([]*v1.TextV1)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllTexts indicates an expected call of GetAllTexts.
func (mr *MockTextServiceMockRecorder) GetAllTexts() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllTexts", reflect.TypeOf((*MockTextService)(nil).GetAllTexts))
}
